### ISSUE TITLE
check NODE_OPTIONS and install instructions for consistency

### ISSUE THREAD

**Issue by Veix123** [robotont/robotont_webapp#4]
In 2ef8740, @sudo-Cthulhufhtagn added --openssl-legacy-provider with NODE_OPTIONS that made webapp work that time with (I reviewed with node v18.13.0). However, I just tested on fresh ubuntu 20.04.5 following the instructions for installing the prerequisites in the readme and got `catkin build` failing.
So I tried bunch of things:
- updated npm with `sudo npm i -g npm`
- removed node_modules folders from frontend and backend directories
- removed package-lock files from frontend and backend directories
- `npm i` in backend and frontend directories
- removed previous build and devel files `rm -fr ~/catkin_ws/devel/.private/robotont_webapp/ ~/catkin_ws/build/robotont_webapp/`
- `catkin build`
... and then I got error: `node: --openssl-legacy-provider is not allowed in NODE_OPTIONS`
I removed the option from package.json and it compiled
Current npm version: 9.5.1, node version: v14.21.3
Seems like older node version does not like this option. Either the install instructions or the code needs a slight update to become consistent.

**Comment by sudo-Cthulhufhtagn** [comment]
Installed and working from scratch in ros container(created from ubuntu 20.04 docker and robotont-setup ansible) with npm version 9.5.0(default installation) and node v19.7.0. Node was updated with:

```
npm install -g n
n latest
```
